import type { GameSchema } from './types'

export const POE1_SCHEMA: GameSchema = {
  LOGIN: {
    title: 'Login',
    keys: {
      gateway_auto_select: { type: 'toggle', label: 'Auto-select gateway' },
      gateway_id: { label: 'Gateway' },
    },
  },
  DISPLAY: {
    title: 'Display',
    keys: {
      device_type: {
        type: 'enum',
        label: 'Renderer',
        options: ['DirectX11', 'DirectX12', 'Vulkan'],
      },
      fullscreen: { type: 'toggle', label: 'Fullscreen' },
      maximize_window: { type: 'toggle', label: 'Maximize window' },
      borderless_windowed_fullscreen: { type: 'toggle', label: 'Borderless windowed' },
      vsync: {
        type: 'enum',
        label: 'V-Sync',
        options: ['On', 'Off', 'Adaptive'],
      },
      shadow_type: {
        type: 'enum',
        label: 'Shadow quality',
        options: ['Off', 'Low', 'Medium', 'High'],
      },
      upscale: {
        type: 'enum',
        label: 'Upscaling',
        options: ['Off', 'FSR', 'DLSS', 'XeSS'],
      },
      upscale_quality: {
        type: 'enum',
        label: 'Upscale quality (FSR/DLSS)',
        options: ['NativeAA', 'Quality', 'Balanced', 'Performance', 'UltraQuality', 'UltraPerformance'],
      },
      upscale_quality_xess: {
        type: 'enum',
        label: 'Upscale quality (XeSS)',
        options: ['NativeAA', 'Quality', 'Balanced', 'Performance', 'UltraQuality', 'UltraPerformance'],
      },
      upscale_resolution: {
        type: 'enum',
        label: 'Upscale resolution preset',
        options: ['NativeAA', 'Quality', 'Balanced', 'Performance', 'UltraQuality', 'UltraPerformance'],
      },
      upscale_sharpness: {
        type: 'slider',
        label: 'Upscale sharpness',
        min: 0,
        max: 1,
        step: 0.05,
        decimals: 2,
      },
      texture_quality: {
        type: 'enum',
        label: 'Texture quality',
        options: ['TextureQualityLow', 'TextureQualityMedium', 'TextureQualityHigh'],
      },
      bloom_strength: {
        type: 'slider',
        label: 'Bloom strength',
        min: 0,
        max: 1,
        step: 0.05,
        decimals: 2,
      },
      depth_of_field: { type: 'toggle', label: 'Depth of field' },
      framerate_limit_enabled: { type: 'toggle', label: 'Framerate limit enabled' },
      background_framerate_limit_enabled: { type: 'toggle', label: 'Background framerate limit enabled' },
      use_dynamic_resolution: { type: 'toggle', label: 'Dynamic resolution' },
      use_dynamic_particle_culling: { type: 'toggle', label: 'Dynamic particle culling' },
      time_manipulation_effects: { type: 'toggle', label: 'Time manipulation effects' },
      quality: { type: 'toggle', label: 'Quality effects' },
      screen_shake_v2: { type: 'toggle', label: 'Screen shake' },
      camera_zrotation: { type: 'toggle', label: 'Camera Z rotation' },
      triple_buffering: { type: 'toggle', label: 'Triple buffering' },
    },
  },
  SOUND: {
    title: 'Sound',
    keys: {
      master_volume2: {
        type: 'slider',
        label: 'Master volume',
        min: 0,
        max: 100,
        step: 1,
      },
      sound_effects_volume2: {
        type: 'slider',
        label: 'Sound effects volume',
        min: 0,
        max: 100,
        step: 1,
      },
      ambient_sound_volume2: {
        type: 'slider',
        label: 'Ambient sound volume',
        min: 0,
        max: 100,
        step: 1,
      },
      music_volume2: {
        type: 'slider',
        label: 'Music volume',
        min: 0,
        max: 100,
        step: 1,
      },
      dialogue_sound_volume2: {
        type: 'slider',
        label: 'Dialogue volume',
        min: 0,
        max: 100,
        step: 1,
      },
      item_filter_sound_volume2: {
        type: 'slider',
        label: 'Item filter sound volume',
        min: 0,
        max: 100,
        step: 1,
      },
      chat_alert_sound_volume: {
        type: 'slider',
        label: 'Chat alert volume',
        min: 0,
        max: 100,
        step: 1,
      },
      reverb_enabled2: { type: 'toggle', label: 'Reverb' },
      mute_in_background: { type: 'toggle', label: 'Mute in background' },
      channel_count: {
        type: 'enum',
        label: 'Audio channels',
        options: ['low', 'medium', 'high'],
      },
    },
  },
  UI: {
    title: 'User Interface',
    keys: {
      key_pickup: { type: 'key', label: 'Pick-up key' },
      minimap_geometry_alpha: {
        type: 'slider',
        label: 'Minimap geometry opacity',
        min: 0,
        max: 1,
        step: 0.05,
        decimals: 2,
      },
      minimap_walkability_alpha: {
        type: 'slider',
        label: 'Minimap walkability opacity',
        min: 0,
        max: 1,
        step: 0.05,
        decimals: 2,
      },
      synthesis_map_zoom: {
        type: 'slider',
        label: 'Synthesis map zoom',
        min: 0,
        max: 1,
        step: 0.05,
        decimals: 2,
      },
      chat_box_font_size: {
        type: 'enum',
        label: 'Chat font size',
        options: ['small', 'normal', 'medium', 'large'],
      },
      always_highlight: { type: 'toggle', label: 'Always highlight items' },
      show_corner_map: { type: 'toggle', label: 'Show minimap' },
      auto_recenter_map: { type: 'toggle', label: 'Auto-recenter map' },
      show_life_levels: { type: 'toggle', label: 'Show life levels' },
      hide_reservation_levels: { type: 'toggle', label: 'Hide reservation levels' },
      show_flask_buffs: { type: 'toggle', label: 'Show flask buffs' },
      show_aura_icons: { type: 'toggle', label: 'Show aura icons' },
      show_ally_mini_life_bars: { type: 'toggle', label: 'Show ally mini life bars' },
      show_enemy_mini_life_bars: { type: 'toggle', label: 'Show enemy mini life bars' },
      show_player_mini_life_bar: { type: 'toggle', label: 'Show player mini life bar' },
      show_global_chat: { type: 'toggle', label: 'Show global chat' },
      show_trade_chat: { type: 'toggle', label: 'Show trade chat' },
      show_guild_chat: { type: 'toggle', label: 'Show guild chat' },
      show_local_chat: { type: 'toggle', label: 'Show local chat' },
      show_party_chat: { type: 'toggle', label: 'Show party chat' },
      show_whisper_chat: { type: 'toggle', label: 'Show whisper chat' },
      show_chat_timestamps: { type: 'toggle', label: 'Show chat timestamps' },
      mouse_wheel_zoom: { type: 'toggle', label: 'Mouse wheel zoom' },
      confine_mouse_to_window: { type: 'toggle', label: 'Confine mouse to window' },
      auto_equip: { type: 'toggle', label: 'Auto equip' },
      tutorials_enabled: { type: 'toggle', label: 'Tutorials enabled' },
      quest_tracking: { type: 'toggle', label: 'Quest tracking' },
      show_clock: { type: 'toggle', label: 'Show clock' },
      output_all_dialogue_to_chat: { type: 'toggle', label: 'Output dialogue to chat' },
      hide_all_filtered_ground_items: { type: 'toggle', label: 'Hide all filtered ground items' },
      show_resistance_icons: { type: 'toggle', label: 'Show resistance icons' },
      use_stash_affinities: { type: 'toggle', label: 'Use stash affinities' },
      affinity_auto_navigation: { type: 'toggle', label: 'Stash affinity auto-navigation' },
      use_guild_stash_affinities: { type: 'toggle', label: 'Use guild stash affinities' },
      guild_affinity_auto_navigation: { type: 'toggle', label: 'Guild affinity auto-navigation' },
      hide_remove_only_tabs: { type: 'toggle', label: 'Hide remove-only tabs' },
      hide_unavailable_tabs: { type: 'toggle', label: 'Hide unavailable tabs' },
      map_overlay_mods_hidden: { type: 'toggle', label: 'Hide map overlay mods' },
      hide_completed_challenges: { type: 'toggle', label: 'Hide completed challenges' },
      corpse_targeting: {
        type: 'enum',
        label: 'Corpse targeting',
        options: ['always', 'never', 'toggle'],
      },
      apply_item_filter_to_ritual: { type: 'toggle', label: 'Apply item filter to ritual' },
      apply_item_filter_to_kalguur: { type: 'toggle', label: 'Apply item filter to Kalguur' },
      expand_map_device_storage: { type: 'toggle', label: 'Expand map device storage' },
    },
  },
  NETWORKING: {
    title: 'Networking',
    keys: {
      networking_type: {
        type: 'enum',
        label: 'Networking type',
        options: ['auto', 'client', 'p2p'],
      },
    },
  },
  GENERAL: {
    title: 'General',
    keys: {
      engine_multithreading_mode: {
        type: 'enum',
        label: 'Multithreading',
        options: ['enabled', 'disabled'],
      },
      enable_profanity_filter: { type: 'toggle', label: 'Profanity filter' },
      disable_tutorials: { type: 'toggle', label: 'Disable tutorials' },
      disable_pausing: { type: 'toggle', label: 'Disable pausing' },
      auto_input_method_switching: { type: 'toggle', label: 'Auto input method switching' },
    },
  },
  CACHED_DATA: {
    title: 'Cached Data',
  },
  Gamepad_UI: {
    title: 'Gamepad UI',
    keys: {
      gamepad_prompt_art: {
        type: 'enum',
        label: 'Gamepad prompt art',
        options: ['auto', 'xbox', 'ps'],
      },
      close_inventory_on_portal_use: { type: 'toggle', label: 'Close inventory on portal use' },
      use_similar_flask_when_empty: { type: 'toggle', label: 'Use similar flask when empty' },
    },
  },
  ACTION_KEYS: {
    title: 'Keybindings',
  },
  NOTIFICATIONS: {
    title: 'Notifications',
  },
  LANGUAGE: {
    title: 'Language',
    keys: {
      chat_language: { label: 'Chat language' },
    },
  },
  TUTORIAL_FLAGS: {
    title: 'Tutorial Flags',
  },
  microtransaction: {
    title: 'Microtransaction',
  },
}
